name: Builds
on:
  push:
  pull_request:

jobs:
  build_for_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          brew install --formula bison mingw-w64 pkgconfig freetype gnutls molten-vk sdl2
      - name: Configure
        run: |
          $GITHUB_WORKSPACE/configure
      - name: Build
        run: |
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
