name: Builds
on:
  push:
  pull_request:

jobs:
  build_for_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          brew install --formula bison mingw-w64 pkgconfig freetype gnutls molten-vk sdl2 gcenx/wine/cx-llvm gettext
      - name: Add bison & cx-llvm to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix cx-llvm)/bin" >> $GITHUB_PATH
      - name: Configure
        run: |
          $GITHUB_WORKSPACE/configure \
            --prefix= \
            --disable-tests \
            --disable-winedbg \
            --enable-win64 \
            --without-alsa \
            --without-capi \
            --with-coreaudio \
            --with-cups \
            --without-dbus \
            --without-fontconfig \
            --with-freetype \
            --with-gettext \
            --without-gettextpo \
            --without-gphoto \
            --with-gnutls \
            --without-gssapi \
            --without-gstreamer \
            --without-inotify \
            --without-krb5 \
            --with-mingw \
            --without-netapi \
            --without-openal \
            --with-opencl \
            --with-opengl \
            --without-oss \
            --with-pcap \
            --with-pthread \
            --without-pulse \
            --without-sane \
            --with-sdl \
            --without-udev \
            --with-unwind \
            --without-usb \
            --without-v4l2 \
            --with-vulkan \
            --without-x
      - name: Build
        run: |
          make -j$(sysctl -n hw.ncpu 2>/dev/null)

      - name: Tar Wine
        run: |
          tar -czvf wine.tar.gz $GITHUB_WORKSPACE

      - name: Upload Wine
        uses: actions/upload-artifact@v3
        with:
          name: "wine"
          path: wine.tar.gz
