name: Builds
on:
  push:
  pull_request:

jobs:
  build_for_mac:
    runs-on: macos-latest
    steps:
      - name: Install prerequisites
        run: |
          brew install --formula bison mingw-w64 pkgconfig freetype gnutls molten-vk sdl2
      - name: Configure
        run: |
          configure
      - name: Build
        run: |
          make
